---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexus-reverse-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: reverse-proxy
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    generateTLS:
      # -- Enable automatic generation of ingress TLS section
      # based on ingress.hosts.*.host
      enabled: true
      # -- certificate to use
      # @default -- default ingress TLS certificate
      secretName: ""
    instances:
      - name: nexus
        # -- enable this reverse proxy.
        # @default -- true
        enabled: true
        # -- add a test for this reverse proxy.
        # It can be tested with `helm test <chart_name>`
        # @default -- true
        test: true
        # -- host name behind this reverse proxy
        externalName: hades.fritz.box
        # -- IP address behind this reverse proxy
        # Has no effect if externalName is set
        #ip: 192.168.1.1
        # -- Port used by host behind this reverse proxy
        # @default -- 80
        port: 8081
        ingress:
          enabled: true
          ingressClassName: "traefik"
          # -- Provide additional annotations which may be required
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            hajimari.io/enable: "true"
            hajimari.io/icon: "weather-sunset"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
          # if not set the generateTLS settigs are used
          tls:
            - hosts:
                - "abc.${SECRET_DOMAIN}"
              secretName: abc-tls
          hosts:
            - host: "abc.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix

    ingressPort:
      # -- Ingress port for non-TLS
      http: 80
      # -- Ingress port for TLS
      tls: 443

    connectionTest:
      # -- seconds to wait before next retry
      waitretry: 2
      # -- second to wait in case no data is received and then try again
      readtimeout: 2
      #   # -- tries to connect
      tries: 30
