---
kubernetes:
  children:
    master:
      hosts:
        k8s-1:
          ansible_host: 192.168.178.71
    worker:
      hosts:
        k8s-2:
          ansible_host: 192.168.178.72
        k8s-3:
          ansible_host: 192.168.178.73
        k8s-4:
          ansible_host: 192.168.178.74
        k8s-5:
          ansible_host: 192.168.178.75
