kind: Secret
ansible_user: ENC[AES256_GCM,data:kFY=,iv:f6IlnBxs02bIMoqK3rGSaO5UWAq4cZWPETbvwv/xx3c=,tag:gAEM9KDy/M37KM3zNV2Pvg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ssegspxWePSg,iv:OEasAAxqjJ8+DVI2uM/RqLXh7v06Hf/TvDj2I4HXClM=,tag:JL8jsY2qG6LLYf1wJokklQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wexpe9gf28hw3x3x4j2slcffptm9w682y4u3zqjejzwue9wh0grsqdmmh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRDBBVzJzaGpRVE1veVpS
            RG45cHJPZG9nK1NNV1A5RlFDUzhTMnprcGxBClFEVGFtdExFRnk1cnpHMmhSVSs4
            M3ExUi9DdnNweno1dFdqTnBsZWZ2ODAKLS0tIGRBeEppcUFUVVZQTUlEbHdWMDFR
            cVRCUGgxbmdoNVdlZzUzSU1yVWtndjQK0HyinBzkNPG23OtHV1gbSGIgH5ZgjrPz
            joFAsOjrNOAa7+Dc7x662d6aNRk6DvRMQrP03vl025XLVSUzrpqEhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T20:32:54Z"
    mac: ENC[AES256_GCM,data:vw8ZcuKIFyBEnUTGMKhEHyvWaohk0v9njx7Uq6NG4Rt1ZHVniJ2V1DaoMDUVfi4LcKO8bVsJfm63u45M8Jzr9NyuV+0Yr/OyYRtQnOstCxEkn26La1FXtp+N8s5IH1mRjOxh529ZWoYpoGKrA4SUDneYY/GmdpSq0T035Cmhgqk=,iv:H/rq2+/Cmgn28yXFjCY/l1R/adxQWSaLN63fp12atzU=,tag:TLxvHNdRarGWx+aGc4CvHA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
