kind: Secret
ansible_user: ENC[AES256_GCM,data:pY8=,iv:F/EDDv0ij4ccE5tMlxUi4CdIY7KI4X2DdVVuu/cgxQA=,tag:o4S4G7K1j/XYX8YqWWSS4A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ie4kh2oEufHO,iv:rPPdJQaPJVVEngIf32l4npENGLB3PVITH+nzo7SpuMM=,tag:nIok0KBi2A7+rG+FPXe3AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wexpe9gf28hw3x3x4j2slcffptm9w682y4u3zqjejzwue9wh0grsqdmmh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN05RT0k5TjBaZFdtWjRl
            NjdiQjgrNi9PQzIwSnoxS0phblNuR3B6cndFCjF4bEltNHJBWngwZ0JWQXVCdWdG
            bnZzdndUOFd5b3hxVG1PTVNsQ2s1dVkKLS0tIFdKR0tWM2dqNjNseGRoOXRya0w5
            MHhJdFIyNEdXRjkvOWJGVzhHZzRtU2cKB87n8VcJWabu6lCLu4719zjyDoweheFc
            u7MXYiibugOmYfMVqlg/2QumLk1qEzpn9/bHo50Hj7p+aLZAa/tr8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T20:32:54Z"
    mac: ENC[AES256_GCM,data:UU/Q9bT/B4LDgj7+2+3iWzdedRUQJfZm6DVijTwZrgfY2NVE6ktZjewLtyblpciAsxQX13xqfW+kseTUde2UXd6FJ8rdMoCD10Mcoe4UIU7wsNIdC/Na4tg0R4LqIv+78ECq1Xge7z3j1y9WSez3T31esbwBfkw8ChtUz7gx1Zg=,iv:5XCGx9U06zjDLLn3LvrJ+aoVjsRe+7amxFh2tw5DftA=,tag:DIjnvIqWnbd0Bwo8yboNqw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
