kind: Secret
ansible_user: ENC[AES256_GCM,data:g1k=,iv:Pqauz2F+T/d3fUPSmrRhf10GjsKATOP3pKdb3fsKIyo=,tag:3cSelm9pjnufqBRc1KwzEw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:DhJ+mlYfMyIY,iv:DUIzD8a+tj4xpqt7uuGY0SnHMUyuZfwGKwxxD2y88so=,tag:rkhoqq/snqJ0XUca8l1JEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wexpe9gf28hw3x3x4j2slcffptm9w682y4u3zqjejzwue9wh0grsqdmmh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSENSd3FkY2hUL1JQV3gz
            M2JaeW8xb3VQT3V0aWdONk1rY1lwRCt0cXhvCnZUSkp3bUp1N3RJK0ppa2lmb0c0
            dU9JYWtBMjl0WUZmSkNMYXZyc2pSRGMKLS0tIDB2SEpDeGR2TTFTWmJGcVBhWXdk
            WEU1Q2FUdWZKbFVJNGZ2ZFV3OThreVEKXkD3hwRhzOb08SQJxP4SuhmV4EbHYs/+
            f651UWZb3d/ovTqAeXt/otQf46qHdMOO6fb1LJo+5wLxEUEOVQdb3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-06T13:29:59Z"
    mac: ENC[AES256_GCM,data:j1sjSCC4/2sluThCSKzzZrX1Z8Wq5yTPicrZ2RgxJMTk5OVlNyCDPggOWNkdRVXGb7YU0wW1551r2EYBjfEeaKTEyF/cUW+E5a5RcvQmBe2l9XF77Tm0rG2NzYg3+YeZa36m7oj92lZiRU20fli96FcjmyGNlvU5B+boSWC1g7c=,iv:o/EwP/W6F37SjJZiNubXzay7J7OGOA3OY0R+X6AmDkU=,tag:NOn/GgGKYdoaIVT9mdvhBw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
