kind: Secret
ansible_user: ENC[AES256_GCM,data:V/g=,iv:trl3TCYz7n5zitez1tTKwIgikSS7i/3Ayq/3+IZcJ7c=,tag:OeJNpSm/BtPtrfEbSgZn/w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SwsCjnAsar1O,iv:PCzsSnMRuC2mmFrR7uTZcng9E1BKsl//naTIdd7IIq0=,tag:z2sjrFEJIOmuISyrpTt19w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wexpe9gf28hw3x3x4j2slcffptm9w682y4u3zqjejzwue9wh0grsqdmmh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS2txR2NrZktGQzJUa0Qv
            WXBlSnlyL09kSkVCVXlVUUNzeHBuRERjNjJJCnE3VllLK2V3TnNwTVRBOVkvYXZp
            b1BrNGNxVDNiTU1XTFo5bHV2UHNNT3MKLS0tIDU4bkYyNEZEbmRUblVaUXVkcURX
            UUsyWm8rL3hsWmY4L0hyekJSODhjMUEKOaiAnOzkYr96sBjpyQJzGQg2IFmEy5DK
            GLxY87b5txTC+mmzTAZ9b3njMcuVNrvEQD+AoNh5sJ/Rosj40n8KKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-06T13:53:56Z"
    mac: ENC[AES256_GCM,data:jd/s0DDC272+nr+zSx8vpdmOMgZs7mfZQFkHzWouItnP7ULjQFDJAQonYbtaQ31/anwP03Y0BqhU6/HH+rbytBxoimGPVtorw1hgUsGWRp6zjjlzsRnEH2Z4oWCbwbPyZZOC/dlqTGp/0PfYKiyd7S4IQ8VAvxbQFfyDANlvNms=,iv:wtgDv5ntKvCkPOXF6zj1lYx4wsJA6KY6kKJt12I+Iz8=,tag:v5iFCkwD2ERfPoxiCLqlbg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
