# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WYT+yu+oWL46a4CZ,iv:Umergic2xiWvWr5oAXohQTgn7/WSjLJUgyx9jabgY6g=,tag:C9qvGXJf2H/6Qo72T9mi/g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:1Il2TCYWAK9LOVZ8rp07KLqZ2wrM6JUV8Lc=,iv:U8N4X324F1FAtRXYmFXwhcFm/nhyZjNXldnrh+Gii0g=,tag:JgFMA3XXIJsu9SJmd/Txew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wexpe9gf28hw3x3x4j2slcffptm9w682y4u3zqjejzwue9wh0grsqdmmh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndllUQnpNdUU4QXM0MmV5
            YU9Vb0gxTi9zUmxLajM1MmE5WGtsT0xEeFFVCjZKaXVIMlUyK3VOQnZSZGgzcE9I
            bGZCQ3NsL2Qwa09SRkNUdVIycy84RDAKLS0tIHpkTkdPVFJIRjk2VVVzV0pEcWJ3
            dEs0OS9pZXRPTCtUQmxaY0tzc3diWmMKPbldMqFvVaPmSJMAAWgUidmJjILpQVCI
            4zRcduGbwV8AV+Ya9VCUmeq6fgvJiAGx5HFkBC8FfFIvDHTXu3me3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T20:32:54Z"
    mac: ENC[AES256_GCM,data:F94cKNpIuQYARRwmRrC1HLjKTYuAW3WbwWPH5+o5gvWHo4DZdgC1dkqd2w+eitPDhSDuYMbc5GmJ0eJpLve438AF2YytsqyZuSR0AufRF8/dCMNV7U20yeI5xye7bI7rwcV3wDN2dosqqy9G2Xvy8BFckzfoxK220oIAUnGgg6g=,iv:KbSGBGXosRGy7ZZiKaiz+f0NlNy+oNJ+PHj7O0VYMhY=,tag:Xn+tkpt/k59aQUCYizCr6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
