---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tandoor-pvc
  namespace: default
  #labels:
  # kasten-io-snapshots: "enable"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 256Mi
