---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: recipes
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vabene1111/recipes
      tag: 1.0.2
    sidecar:
      image:
        # -- nginx sidecar image repository
        repository: nginx
        # -- nginx sidecar image tag
        tag: 1.20.2-alpine
        # -- nginx sidecar image pull policy
        pullPolicy: IfNotPresent
    env:
      TIMEZONE: Europe/Berlin
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "${SECRET_TANDOOR_SECRET_KEY}"
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: "${SECRET_TANDOOR_POSTGRES_HOST}"
      POSTGRES_PORT: "${SECRET_TANDOOR_POSTGRES_PORT}"
      POSTGRES_USER: "${SECRET_TANDOOR_POSTGRES_USER}"
      POSTGRES_DB: "${SECRET_TANDOOR_POSTGRES_DB}"
      POSTGRES_PASSWORD: "${SECRET_TANDOOR_POSTGRES_PASSWORD}"
      GUNICORN_MEDIA: "0"
      FRACTION_PREF_DEFAULT: "0"
      COMMENT_PREF_DEFAULT: "1"
      SHOPPING_MIN_AUTOSYNC_INTERVAL: "5"
    persistence:
      config:
        enabled: true
        existingClaim: nfs-tandoor-pvc
      media:
        enabled: false
        mountPath: /opt/recipes/mediafiles
      static:
        enabled: true
        type: emptyDir
        mountPath: /opt/recipes/staticfiles

    service:
      main:
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: tcp

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          ajimari.io/enable: "true"
          hajimari.io/icon: "shield-half-full"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "tandoor.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub/negotiate
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                servicePort: 3012
        tls:
          - hosts:
              - "tandoor.${SECRET_DOMAIN}"
            secretName: "tandoor-tls"
            #secretName: "${SECRET_CLUSTER_CERTIFICATE_DEFAULT}"
