# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:VCfKsTX1BjFbmzQs+WQ6TNag7QW2RDJewTNmKJurKvG7F71Dvw==,iv:aIaQq5mV9zmpUEXNOrzshMeJ4eEopt+ewxWmVUmKz98=,tag:0KXKWzVqbzZmCuBd9Y26sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wexpe9gf28hw3x3x4j2slcffptm9w682y4u3zqjejzwue9wh0grsqdmmh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdnZ3Sk1MOUk2NU93cXVY
            dW01QStDR2szWkN6eUNGd3RrSzBENzFMbmtVCjJOTW54UExaQ0lLM2cvb1N0SElO
            U2dwWEtkNU5GVG1GNjUvMjdPaHJDWFUKLS0tIEZuUGdnWThJV2U2aytpQ0x5OThE
            MDd3c1B0OFlRRWZobTJTSU4vVytkczAKHRvr5Va2Fvgatj0IlIWitOeKVss3mMlV
            fXo8jpXUdrgszqwFF9yt92AvpEsmF6ipxv32n7W3Xr24kjNI7V6Y9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-06T13:53:56Z"
    mac: ENC[AES256_GCM,data:m5iiVCcr/FdOwEXQZ5SiMwVaNNHTYtioUlKxYxCIHC3S8kiWpjsF/M+CdiZFdvHgnjT7ZBUehTWgnAdQGRZ/gbF82J5ZDgEIP6lhVUSb23DMzaQx1bCf7S4dOKOnkngyZwFUjFaXzJrgbUWgj5pRd+D/N0ZF9NFXRcPHHFMaIH4=,iv:m091dpD41t1HrwGHaaOR3sserdKywPB1iM6WPjTtVso=,tag:xJ9Uw9fDZo7OsTb8kKJyQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
