---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: hajimari-nfs-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hajimari-nfs-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  nfs:
    path: /volume2/nfs/hajimari
    server: 192.168.178.88
  mountOptions:
    - nfsvers=4.2
