---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: hajimari-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hajimari-pv
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
